/*
 * This source file was generated by the Gradle 'init' task
 */
package prak1.putu.eka.adi.saputra;


public class App {
    public String getGreeting() {
        return "Hello Eka!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
